name: Tests

on: [push]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build and run tests in Docker
      run: env USE_DOCKER=1 ./build-and-test.sh
